### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by valli180** [UBC-MDS/olympics_data_analysis#77]
Changes made to app.py
1) Change the age distribution bar plot to KDE plot
2) Added Data Tab with tables
3) Add Country Filter
4) Aesthetics changes like adding Background colour and changing the font colour and theme.
5) Remove the redundant axes for age and medals distribution plots

**Comment by Sanchit120496** [comment]
We have not included point 3 and point 5. 

There is no particular theme in the feedback. We planned to include the `Country` to go along with the other filters, but, owing to the time constraint, we could not implement it because that would require wrangling data at different levels for each graph.
